name: paseto_dart
description: Unofficial PASETO implementation for Dart
version: 2.1.0
homepage: https://github.com/nogipx/paseto_dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cryptography: ^2.9.0
  equatable: ^2.0.8
  meta: ^1.18.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0

false_secrets:
 - /test/vectors/v4.json